### ISSUE TITLE
No code?

### ISSUE THREAD

**Issue by iComplain** [KawaCoder/Anti-AFK-kick-for-all-games#2]
Why is there no code?

**Comment by KawaCoder** [comment]
Hy I think you did not search enough before asking your question. The source code is in Main.java.
Have a nice day M. "I Complain"

**Comment by iComplain** [comment]
Oh MB, its just every time I use it in 'tampermonkey' it doesn't work.

**Comment by KawaCoder** [comment]
It is a java code for desktop app, not a javascript snippet.
